"""Metrics and solver signals description (code truth source).

This module provides the authoritative description of metrics and solver signals
used in the AgenQA system. This content is referenced by prompts that need to
understand how to interpret solver results and metrics.
"""

from __future__ import annotations

from textwrap import dedent

EDGE_QA_VS_PATH_DESCRIPTION_ZH = dedent(
    """\
    ## Edge QA vs Path QA

    AgenQA 在每个 step 会维护两种“同一目标、不同视角”的评测视角：

    - **Edge QA**：solver 可见 edge 视角（`premise_bank + fact_bank/step_certs(<t)`；不含 episode_seed）。
      - 直观上：这是“只看当前边：step_{t-1} → step_t”的评测；solver 允许复用前序结论，因为这些结论在可见上下文里。
    - **Path QA（Path-Fold）**：solver 只可见 path 起点视角（仅 `premise_bank`；不含 episode_seed），但题目会先对整条路径做一次“路径折叠”再求解。
      - 也就是说：Path QA 下的 `Question` **不要求**与 Edge QA 的 `Question` 相同；它来自“路径折叠器”生成的新题面 `Q_fold`，其目标是让 solver 从起点 P 直接推到 `Answer_t`。
      - 当前实现会产出两个变体：
        - `direct`：不提示中间量，只问最终目标（更难）。
        - `scaffolded`：用子任务/分问提示中间推理目标，但不赠送中间结论（更易）。

    **重要约束**：
    - 约束一（Path-Fold 复用安全）：折叠题 `Q_fold` 必须 **严禁**任何“跨步/跨 history 的指针式引用”，包括但不限于：
      - 禁止：“使用上一步结果 / 上题结论 / 根据 step X / 如上所示 / 由前序可知 …”
      - 禁止：任何依赖 `history/fact_bank/step_certs` 的引用（Path QA 视角看不到这些内容）
      - 允许：`Q_fold_scaffolded` 在同一题面内给出分问/子目标，并引用同一题面内前面小问/子任务的结果（例如“利用(1)的结果继续求(2)”），因为解题者可在题面内复现这些中间量。
      - 关键点：Path QA 的 solver 视角看不到 history，因此“跨步指针”会把题面变成对 hidden context 的依赖，诱导系统用“泄露补洞”。
    - 约束二（Edge QA 允许复用）：Edge QA 的 solver 视角**可见** `fact_bank/step_certs(<t)`，因此题面允许显式表达“使用前序结论/根据上一步结果”等依赖关系（它不再是 hidden dependency）。
      - 但更推荐把复用关系落在结构化元数据（`fact_bank/step_certs`、`draft_chain.required_fact_ids` 等）中；题干里若出现“从 step X”这类指针，尽量只作为说明性锚点，避免大段复制粘贴前序答案造成冗余或不一致。
    - 约束三（等价目标）：Path 折叠题 `Q_fold` 的最终答案必须与 tail step 的 `Answer_t` **语义等价**（同一个可机判答案）。
    - 约束四（不赠送中间结论）：`Q_fold` 可以提示中间推理目标（scaffolded），但严禁把任何中间结论写成已知；尤其严禁把 history 中任一步的 Answer（或等价表述）贴进题干。
    - **Premise 聚合风险**：Path 视角会始终可见 `premise_bank`，因此 `premise_bank` 只能写“前提/定义/条件”，严禁写入推导结论，否则会长期污染后续 Path QA 评估。

    备注：
    - `episode_seed` 是出题侧的“话题锚定/元信息”，用于 Director/出题者侧一致性检查与生成引导；它不进入 solver 输入。
    """
)

EDGE_QA_VS_PATH_DESCRIPTION_EN = dedent(
    """\
    ## Edge QA vs Path QA

    AgenQA evaluates each step under two evaluation views:

    - **Edge QA**: the solver sees the edge view (`premise_bank + fact_bank/step_certs(<t)`; no episode_seed).
      - Intuition: it evaluates the current edge `step_{t-1} → step_t`; reuse of prior-step results is allowed because they are visible.
    - **Path QA (Path-Fold)**: the solver sees the path start view only (`premise_bank` only; no episode_seed), but the question is generated by folding the whole path into a single problem.
      - In other words, the Path QA `Question` is **not required** to be identical to the Edge QA `Question`. Instead, a path-folding role produces a new question `Q_fold` whose goal is to make `Answer_t` derivable directly from the start P.
      - Two variants are produced:
        - `direct`: asks the final target only (harder).
        - `scaffolded`: lists intermediate sub-goals as hints but does not give away intermediate results (easier).

    **Key constraints**:
    - Constraint 1 (Path-Fold reuse safety): the folded question `Q_fold` must not contain any pointer-style references to prior steps/history, including but not limited to:
      - Forbidden: “use the previous step’s result”, “from step X”, “as shown above”, “given the previous conclusion …”
      - Forbidden: any reference that assumes access to `history/fact_bank/step_certs` (not visible in Path QA)
      - Allowed: the scaffolded folded prompt may include sub-questions/sub-goals and refer to results from earlier sub-parts within the *same* folded prompt (e.g., “use the result from (1) to solve (2)”), since those are reproducible inside the prompt.
      - Key point: under Path QA the solver cannot see history, so cross-step pointers create hidden-context dependencies and push the system toward leakage-based “patching”.
    - Constraint 2 (Edge QA allows reuse): in Edge QA, the solver **does see** `fact_bank/step_certs(<t)`, so the question may explicitly reference prior-step results (it is no longer a hidden dependency).
      - Still, prefer to keep reuse in structured metadata (`fact_bank/step_certs`, `draft_chain.required_fact_ids`) and only use “from step X” as a lightweight anchor; avoid copy-pasting large chunks of prior answers that can become redundant or inconsistent.
    - Constraint 3 (answer equivalence): the folded `Q_fold` must be answer-equivalent to the tail step’s `Answer_t` (same machine-checkable final answer).
    - Constraint 4 (no intermediate giveaways): `Q_fold` may hint intermediate goals (scaffolded), but must not paste any intermediate result as a given (especially any step’s Answer or its paraphrase).
    - **Premise aggregation risk**: Path QA always includes `premise_bank`, so it must contain only *premises/assumptions/definitions* and never derived conclusions; otherwise it permanently contaminates later Path QA evaluations.

    Note:
    - `episode_seed` is generator-side topic-anchor metadata used by Director/generation roles; it is not included in solver input.
    """
)

METRICS_AND_SOLVERS_DESCRIPTION_ZH = dedent(
    """\
    关于 `metrics` 与 solver 结果（仅供内部角色理解，尤其是 Director 与算子）：
    - 我们评测同一个 step 的题目时，会同时跑两种视角：Edge QA 与 Path QA（概念定义见 `EDGE_QA_VS_PATH_DESCRIPTION_ZH`）。
    - 对于 **Edge QA**（默认聚合视角）：
      - `metrics.edge.correct_medium` 表示 medium solver 在当前题上的对错；
      - `metrics.edge.strong_summary` 提供 multi-strong 聚合摘要（`total/explicit_total/correct_count/incorrect_count/unknown_count/all_correct/any_incorrect`）；
      - `metrics.edge.token_ratio_medium` 是基于“输出 tokens / 输入 tokens”的 token 比例（仅在答对时更有意义），数值越大通常表示推理链更长、题目更复杂。注意：这是相对指标，不能作为绝对难度，也不能用于跨模型比较。
      - `metrics.edge.kq_tokens_step_ratio_*` / `metrics.edge.completion_tokens_step_ratio_*` 是 step(t) 相对 step(t-1) 的 tokens 趋势比值（缺失时按 1 处理），用于观察“上下文长度/输出长度”的递进趋势；仅作弱参考，不能作为绝对难度或跨模型比较依据。
      - 更完整的条目可见 `solver_metrics.edge.tool/medium/strong`（含 model / service_id）。
      - 备注：`solver_metrics.*.*.extra` 可承载“模式相关”的扩展信号（字段不固定）。
      - tool tier 说明：tool solver 允许输出可执行代码（内部运行）辅助数值计算/验证，通常用于 Numeric（难度梯度的一档）。**工具产物必须视为内部工件**，不得写入 premise_bank 或泄露到 Path 题面。
    - 对于 **Path QA**：
      - 若已运行 path 求解，则 `metrics.path.correct_medium` 提供 path-medium 对错；
      - `metrics.path.strong_summary` 提供 path multi-strong 聚合摘要（同 edge）；
      - `metrics.path.kq_tokens_step_ratio_*` / `metrics.path.completion_tokens_step_ratio_*` 是 Path 视角的 step-to-step tokens 趋势比值（缺失时按 1 处理），仅作弱参考。
      - 更完整的条目可见 `solver_metrics.path.tool/medium/strong`（含 model / service_id）。
      - 备注：`solver_metrics.*.*.extra` 可承载“模式相关”的扩展信号（字段不固定）。
    - Director 与算子解读直觉（原则化，不用硬阈值）：
      - edge‑medium/strong 同时正确：题目局部自洽，可参考 strong 的反馈决定继续 Extend 还是压缩/重构；
      - medium 正确 / strong 错误：题目可能存在歧义或表达式/口径问题，优先结合 strong 的 feedback 做小修（Revise correctness）；
      - edge‑medium/strong 都错误：题目可能不 well-posed 或难度过高，优先让 Director 决定是否 Revise/Compress 或终止；
      - edge‑tool 正确但 medium/strong 错：常见于“题目逻辑自洽但算术/数值推演重、易心算失误”，可视为“工具可解但人难算”的信号；可用来诊断是否应减少纯算术负担、或明确数值口径/单位，或保持为高难 Numeric。
      - edge 正确但 path 错：常见于“端到端折叠题很难/需要步骤化脚手架”，通常说明链条分步递进具有价值；也可能是折叠题不 well-posed（需 Diagnose/Revise）。
      - path 也能解对：说明从起点 P 到当前答案在折叠题下是可达的；警惕折叠题是否提示过强（尤其 scaffolded 版本）或链条可以被压缩。
    """
)

METRICS_AND_SOLVERS_DESCRIPTION_EN = dedent(
    """\
    About `metrics` and solver results (for internal roles, especially Director and operators):
    - We evaluate the same step under two views: Edge QA and Path QA (see `EDGE_QA_VS_PATH_DESCRIPTION_EN`).
    - For **Edge QA** (the default aggregated view):
      - `metrics.edge.correct_medium` indicates medium-solver correctness for the current question.
      - `metrics.edge.strong_summary` provides multi-strong aggregate stats (`total/explicit_total/correct_count/incorrect_count/unknown_count/all_correct/any_incorrect`).
      - `metrics.edge.token_ratio_medium` is the token ratio based on "output tokens / input tokens" (most meaningful when the answer is correct); larger values usually mean longer reasoning chains and higher complexity. Note: this is a relative signal, not an absolute difficulty indicator, and cannot be used for cross-model comparison.
      - `metrics.edge.kq_tokens_step_ratio_*` / `metrics.edge.completion_tokens_step_ratio_*` are step-to-step token trend ratios (step(t) vs step(t-1), defaulting to 1 when missing), used as weak within-run trend signals for input/output length; do not treat them as absolute difficulty or compare across models.
      - Full entries are available in `solver_metrics.edge.tool/medium/strong` (including model / service_id).
      - Note: `solver_metrics.*.*.extra` may carry mode-specific extension signals. The keys are not fixed.
      - Tool tier note: the tool solver may output executable code (run internally) to compute/verify numeric values, typically for Numeric questions (a difficulty-gradient tier). Tool artifacts are internal-only and must not be written into premise_bank or leaked into Path questions.
    - For **Path QA**:
      - When path solving is run, `metrics.path.correct_medium` provides path-medium correctness.
      - `metrics.path.strong_summary` provides path multi-strong aggregate stats (same shape as edge).
      - `metrics.path.kq_tokens_step_ratio_*` / `metrics.path.completion_tokens_step_ratio_*` are step-to-step token trend ratios for the path view (defaulting to 1 when missing); treat them as weak signals only.
      - Full entries are available in `solver_metrics.path.tool/medium/strong` (including model / service_id).
      - Note: `solver_metrics.*.*.extra` may carry mode-specific extension signals. The keys are not fixed.
    - Intuitive guidelines:
      - edge‑medium and edge‑strong both correct: the step is locally sound; you may use strong feedback to decide whether to Extend or Compress/Refactor.
      - medium correct but strong wrong: likely ambiguity/notation issues; prefer a small correctness-focused Revise.
      - both medium and strong wrong on edge: likely not well-posed or overly hard; let Director decide Revise/Compress/Finish.
      - edge‑tool correct but medium/strong wrong: often indicates the task is internally consistent but numerically heavy or error-prone without a calculator; use it to diagnose whether to reduce arithmetic burden, clarify units/tolerance, or intentionally keep it as a hard Numeric.
      - edge correct but path wrong: often means the folded end-to-end task is hard and stepwise scaffolding adds value; it can also indicate `Q_fold` is not well-posed (Diagnose/Revise).
      - path also correct: suggests the final answer is reachable from the start P under the folded task; watch for overly strong hints (especially the scaffolded variant) or that the chain can be compressed.
    """
)
